CREATE TABLE MERCTRL (
   MERNBR               VARCHAR(128)           NOT NULL,
   MERSTATUS            CHAR(1),
   MERBEGIN           VARCHAR(16),
   MEREND             VARCHAR(16),
   MEMO1              VARCHAR(128),
   MEMO2              VARCHAR(128),
   MEMO3              VARCHAR(128),
   DATELASTMAINT      TIMESTAMP
);

COMMENT ON TABLE MERCTRL IS
'商户控制表';

COMMENT ON COLUMN MERCTRL.MERNBR IS
'商户号';

COMMENT ON COLUMN MERCTRL.MERSTATUS IS
'开通状态:0-关1-开';

COMMENT ON COLUMN MERCTRL.MERBEGIN IS
'失效时间:YYYYMMDDhhmmss按照GMT+8时间返回';

COMMENT ON COLUMN MERCTRL.MEREND IS
'生效时间:YYYYMMDDhhmmss按照GMT+8时间返回';

COMMENT ON COLUMN MERCTRL.MEMO1 IS
'备注1';

COMMENT ON COLUMN MERCTRL.MEMO2 IS
'备注2';

COMMENT ON COLUMN MERCTRL.MEMO3 IS
'备注3';

COMMENT ON COLUMN MERCTRL.DATELASTMAINT IS
'最后更新时间';

ALTER TABLE MERCTRL
   ADD CONSTRAINT PK_MERCTRL PRIMARY KEY (MERNBR);

INSERT INTO MERCTRL (MERNBR, MERSTATUS, MERBEGIN, MEREND, MEMO1, MEMO2, MEMO3, DATELASTMAINT) VALUES ('1', '1', '1', '1', '考考', '1', '1', TIMESTAMP '2018-12-12 00:00:00');

--序列
CREATE SEQUENCE seq_mer START WITH 1000 INCREMENT BY 10;
--查询
SELECT seq_mer.nextval FROM dual;

SELECT seq_mer.currval FROM dual;